name: CD - Release & Publish JAR — Apache Ranger Plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write   # needed to push tags and create releases

jobs:
  publish:
    runs-on: ubuntu-latest
    # only run publish after a merge pushed to main
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags origin

      - name: Determine or create release tag (reuse existing tag from feature if present)
        id: determine_tag
        run: |
          set -e
          COMMIT=${GITHUB_SHA}
          echo "Merged commit: $COMMIT"

          TAG=""
          # iterate tags newest first and find first tag whose commit is ancestor of merged commit
          while read -r tagName tagSHA; do
            if git merge-base --is-ancestor "$tagSHA" "$COMMIT"; then
              TAG="$tagName"
              break
            fi
          done < <(git for-each-ref --sort=-creatordate --format='%(refname:short) %(objectname)' refs/tags)

          if [ -n "$TAG" ]; then
            echo "Found existing tag reachable from merge: $TAG"
          else
            SHORT_SHA=$(echo $COMMIT | cut -c1-7)
            TAG=release-${SHORT_SHA}-$(date +%Y%m%d%H%M%S)
            echo "No existing tag found; creating tag: $TAG"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git tag -a "$TAG" -m "Release tag for merged commit $COMMIT"
            git push origin "$TAG"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Determined tag: $TAG"
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build shadow JAR with release tag
        run: |
          echo "Building with releaseVersion=${{ steps.determine_tag.outputs.tag }}"
          ./gradlew :apache-ranger-plugin:clean :apache-ranger-plugin:shadowJar --no-daemon -PreleaseVersion=${{ steps.determine_tag.outputs.tag }}

      - name: Locate built JAR (now with tag-version)
        id: findjar
        run: |
          set -e
          TAG=${{ steps.determine_tag.outputs.tag }}
          JAR=$(ls apache-ranger-plugin/build/libs/apache-ranger-plugin-${TAG}*.jar 2>/dev/null | head -n 1 || true)
          if [ -z "$JAR" ]; then
            # fallback to any file if naming differs
            JAR=$(ls apache-ranger-plugin/build/libs/apache-ranger-plugin-*.jar | head -n 1 || true)
          fi
          if [ -z "$JAR" ]; then
            echo "No jar found" >&2
            ls -la apache-ranger-plugin/build/libs || true
            exit 1
          fi
          echo "jar=$JAR" >> $GITHUB_OUTPUT
          echo "Built JAR: $JAR"
          
      - name: Set up JDK 11 and Maven settings for publishing
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.PAT_TOKEN }}
      
      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.determine_tag.outputs.tag }}
          name: ${{ steps.determine_tag.outputs.tag }}
          files: ${{ steps.findjar.outputs.jar }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to GitHub Packages (Maven)
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # pass releaseVersion to gradle so publishing coordinates match tag if needed
          ./gradlew :apache-ranger-plugin:publish --no-daemon -PreleaseVersion=${{ steps.determine_tag.outputs.tag }}