name: CI - Build — Apache Ranger Plugin

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run build and produce fat JAR (shadow)
        run: ./gradlew :apache-ranger-plugin:clean :apache-ranger-plugin:shadowJar --no-daemon

      - name: Locate built JAR
        id: findjar
        run: |
          set -e
          JAR=$(ls apache-ranger-plugin/build/libs/apache-ranger-plugin-*.jar 2>/dev/null | head -n 1 || true)
          if [ -z "$JAR" ]; then
            echo "No jar found in apache-ranger-plugin/build/libs/" >&2
            ls -la apache-ranger-plugin/build/libs || true
            exit 1
          fi
          echo "jar=$JAR" >> $GITHUB_OUTPUT
          echo "Found: $JAR"

      - name: Upload built JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: apache-ranger-plugin-jar
          path: ${{ steps.findjar.outputs.jar }}